%%% @doc A sighting's identity is the observation, not the delivery.
%%%
%%% The id used to be `crypto:strong_rand_bytes/1', minted per mesh delivery, so
%%% a redelivered warden fact became a second event and inflated the evidence
%%% log permanently. On a mesh with known redelivery behaviour that is a live
%%% defect, not a theoretical one. These pin both halves of the fix: the id is
%%% derived from the observation, and the aggregate refuses a duplicate once the
%%% stream already holds it.
-module(sighting_identity_tests).
-include_lib("eunit/include/eunit.hrl").

-define(IP, <<"203.0.113.7">>).
-define(AT, 1785215553616).

%% --- the id ---

%% THE REGRESSION. Two deliveries of one observation must address one stream.
same_observation_yields_same_id_test() ->
    ?assertEqual(id(fact()), id(fact())).

%% Each discriminating field must actually discriminate, or two genuinely
%% distinct observations collapse into one and we lose evidence.
distinct_observations_yield_distinct_ids_test() ->
    Base = id(fact()),
    ?assertNotEqual(Base, id(fact(#{source_ip => <<"198.51.100.9">>}))),
    ?assertNotEqual(Base, id(fact(#{label => <<"paris">>}))),
    ?assertNotEqual(Base, id(fact(#{at => ?AT + 1}))),
    %% `service' is in the key because two sensors on one warden can report the
    %% same IP in the same millisecond for different services.
    ?assertNotEqual(Base, id(fact(#{service => <<"http">>}))).

%% The warden component follows warden_key/2: the stable label when there is
%% one, the ephemeral DID otherwise. A warden that restarts keeps its label, so
%% its sightings stay addressable across the restart.
unlabeled_warden_falls_back_to_the_reporter_test() ->
    A = id(fact(#{label => undefined, warden => <<"did:one">>})),
    B = id(fact(#{label => undefined, warden => <<"did:two">>})),
    ?assertNotEqual(A, B),
    ?assertEqual(A, id(fact(#{label => undefined, warden => <<"did:one">>}))).

label_wins_over_reporter_test() ->
    %% Same box, DID regenerated by a restart: still one identity.
    ?assertEqual(id(fact(#{warden => <<"did:one">>})),
                 id(fact(#{warden => <<"did:two">>}))).

id_is_shaped_like_the_one_it_replaces_test() ->
    Id = id(fact()),
    ?assertEqual(32, byte_size(Id)),
    ?assertMatch({match, _}, re:run(Id, <<"^[0-9a-f]{32}$">>)).

%% --- the aggregate guard ---

%% Without this the deterministic id only makes duplicates ADDRESSABLE, not
%% rejected: execute/2 ignored state and emitted unconditionally, so the second
%% delivery appended a second identical event to the same stream.
recorded_sighting_refuses_a_duplicate_test() ->
    {ok, Fresh} = threat_aggregate:init(<<"sight-abc">>),
    Cmd = command(),

    {ok, [Event]} = threat_aggregate:execute(Fresh, Cmd),

    Recorded = threat_aggregate:apply(Fresh, Event),
    ?assertEqual({ok, []}, threat_aggregate:execute(Recorded, Cmd)).

%% apply/2 used to discard the event and return State unchanged, so a replayed
%% aggregate loaded to an empty state and could never tell recorded from new.
apply_folds_the_event_into_state_test() ->
    {ok, Fresh} = threat_aggregate:init(<<"sight-abc">>),
    ?assertNotMatch(#{recorded := true}, Fresh),
    ?assertMatch(#{recorded := true}, threat_aggregate:apply(Fresh, #{})).

unknown_commands_are_still_rejected_test() ->
    {ok, Fresh} = threat_aggregate:init(<<"sight-abc">>),
    ?assertEqual({error, unknown_command},
                 threat_aggregate:execute(Fresh, #{command_type => <<"nope">>})).

%% --- helpers ---

fact() -> fact(#{}).

fact(Overrides) ->
    maps:merge(#{source_ip => ?IP,
                 warden    => <<"did:web:example#warden">>,
                 label     => <<"helsinki">>,
                 service   => <<"ssh">>,
                 attempts  => 5,
                 window_s  => 300,
                 usernames => [<<"root">>],
                 at        => ?AT},
               Overrides).

%% Drives the real derivation, so the test breaks if it changes.
id(#{source_ip := Ip, label := Label, warden := Reporter,
     service := Service, at := At}) ->
    ingest_warden_reports:sighting_id(Ip, Label, Reporter, Service, At).

command() ->
    #{command_type => <<"report_threat">>,
      sighting_id  => <<"abc">>,
      reporter     => <<"did:web:example#warden">>,
      label        => <<"helsinki">>,
      source_ip    => ?IP,
      service      => <<"ssh">>,
      attempts     => 5,
      window_s     => 300,
      usernames    => [<<"root">>],
      at           => ?AT}.
